cluster/juju/layers/kubernetes/templates/master.json

The Juju cluster fails to bring up the apiserver. Using the docker logs I see the API server complaining about a fatal error.
```
F0830 17:04:16.922997       1 plugins.go:143] Unknown admission plugin: DefaultStorageClass
```
**Which issue this PR fixes** : fixes #31726

Removing the Storage plugin from the list

---

cluster/juju/layers/kubernetes/README.md
cluster/juju/layers/kubernetes/metadata.yaml

This PR updates the juju charm code to support the latest series (xenial 16.04). We changed the README to reflect this change and how that changes the juju commands.
fixes #30373
`release-note-none`
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30374)

Update the series and the README to reflect the change.

---

cluster/juju/layers/kubernetes/tests/tests.yaml

Juju bootstrapping is an act of cost. This should be an explicit action
by the tooling surrounding bundle-tester when testing a charm. Setting
bootstrap:false will allow us to get faster feedback at lower cost when
running the kubernetes charm under ci.

Automated testing shouldn't bootstrap

---

cluster/juju/layers/kubernetes/reactive/k8s.py

**What this PR does / why we need it**: Corrects the locked messaging on the master unit
```release-note
None
```
Removes a stale state, and now reacts when kubedns is available as it
should.

Fixes messaging on the master unit

---

cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py

This directive tells kubelet how to contact the master apiserver node(s)
during cluster turn up. This is required when not using the deprecated
--apiservers flag to the kubelet binary

Adds --require-kubeconfig flag to kubelet

---

cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py

This will cause errors during cluster turnup without having the --'s,
they get rendered in teh manifest without their flags and instead are
interpreted as arguments to other flags.

DNS options were being added without flags

---

cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py

This patch makes the master wait until the prerequisit tools are
available before attempting to generate kubeconfig files

Decorate the certificates logic to halt for tools

---

cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py

There are transient states during turn up that can be confusing to the end 
user. This branch attempts to clean up those scenarios with clear messaging
to the user to set expectations.                                           
- kubelet is waiting on cluster dns                                        
- kubelet is not running                                                   
- kubelet needs to negotiate running the dns container with the master     
Removes the caching `data_changed` stanza on the cluster certificates      
management                                                                 
Adds new tls-client states to guard against unwritten file race conditions 
during turnup.

Remove worker caching states and re-work the user messaging

---

cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py
cluster/juju/layers/kubernetes-worker/templates/default-http-backend.yaml

default-http-backend as a service to establish endpoint routing out of
the box when ingress is enabled

Move the expose declaration into the manifest, and provide

---

cluster/juju/layers/kubernetes-worker/templates/kubelet.service

Don't merge yet - needs testing.
Proposed fix for cAdvisor "too many open files" error, which occurs when we hit the inotify instance limit defined by sysctl `fs.inotify.max_user_instances`.
Every time kubelet restarts, we see a leaked `journalctl -k -f` child process which is consuming inotify instances. Eventually, we hit the limit and can no longer start kubelet.
Fix is to remove `KillMode=process`, so we default to the `control-group` policy instead, which kills the whole process group.
Another factor in this is that `kubelet` is restarting every time the juju `update-status` hook runs - that is being looked into separately.
@chuckbutler @mbruzek @wwwtyro

Fix inotify leak by killing child processes

---

cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
cluster/juju/layers/kubernetes-worker/layer.yaml
cluster/juju/layers/kubernetes-worker/metadata.yaml
cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py

- Moving the SDN code to the docker layer required some refactoring of this code.
- Changed the status messages to accommodate the SDN code move.
- Preventing the kubelet/kube-proxy restart on each reactive cycle with data_changed()
- Improved and updated the logging on both worker, and master

Remove sdn

---

cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py

@chuckbutler @mbruzek
Scales the ingress controller replica count to match the number of kubernetes-worker units.
We see a couple of issues with this PR:
1. There's a potential race condition wherein the controller replica count can be set to a value less than the number of kubernetes-worker units. It seems unlikely to occur, but we may need to look into placing this logic elsewhere or running it at some interval instead of only once.
2. The scaling appears to occur serially, at least how we're invoking it here. In our three-node microbot test, each nginx ingress pod took 11 minutes to reach a `Running` state, and it took 33 minutes before we were able to reach microbot because the last nginx ingress pod was the one selected by microbot to serve as its proxy.

scale ingress controller to the number of kubernetes-workers

---

cluster/juju/layers/kubernetes-worker/layer.yaml

Ceph-Common is a required component to interact with ceph clusters.
Adding this to the worker packages works in tandem with the
create-rbd-pv action to enlist persistent volumes from a ceph-cluster
supporting the ceph-admin interface.

Adds ceph-common to the worker packages

---

cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py

Proposed fix for https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/105
The first problem is that kubelet does not pick up the `--cluster-dns=10.1.0.10:53` arg. As a result, pods/containers aren't being configured to use kube-dns. Looks like we're not supposed to pass in the port there, so the fix is to change it to `--cluster-dns=10.1.0.10`. This is a fix to kubernetes-worker.
The second problem is that the clusterIP of the `kube-dns` service differs from the one we send over the kube-dns relation. This happens because we use 'subnet' when calculating the clusterIP, but use 'cidr' when calculating it again to send over kube-dns. Fix this by using 'cidr' in both cases. This is a fix to kubernetes-master. @mbruzek this is the case we looked at yesterday.
Cc @chuckbutler …

Fix kube-dns IP configuration

---

cluster/juju/layers/kubernetes-master/templates/kube-apiserver.defaults

E2E attempts to use container-level SELinux policy maps during it's
evaluation of the cluster, despite having that access control policy
disabled in the apiserver. We will never pass E2e with this enabled.
addresses:
https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/106

Remove the explicit SecurityContextDeny due to failures in e2e

---

cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py

Cleaning up my mess! This fixes two problems:
1. Hook failed during `upgrade-charm`
2. Infinite loop between `launch_kubernetes_dashboard` and `reset_states`
@chuckbutler @mbruzek

dashboard reactive fixes

---

cluster/juju/layers/kubernetes-e2e/README.md
cluster/juju/layers/kubernetes-e2e/actions.yaml

This is still WIP - however i felt it would be good to get early feedback on the README for the e2e layer, as its got a large role to play and I want it to be well understood going into it:
- How we use it
- Why its important
- How to modify its default behavior
- How to get results and furthermore how to interpret them

Adds description to the test action and skeleton readme

---

cluster/juju/layers/kubernetes-e2e/actions/test

@chuckbutler @mbruzek @Cynerva 
```
$ juju run-action kubernetes-e2e/1 test
Action queued with id: c81fa448-c25f-4180-84fe-fdda4a180bda
$ juju show-action-output c81fa448-c25f-4180-84fe-fdda4a180bda
results:
junit: /home/ubuntu/c81fa448-c25f-4180-84fe-fdda4a180bda-junit.tar.gz
log: /home/ubuntu/c81fa448-c25f-4180-84fe-fdda4a180bda.log
status: completed
timing:
completed: 2016-11-02 15:50:59 +0000 UTC
enqueued: 2016-11-02 15:44:31 +0000 UTC
started: 2016-11-02 15:44:35 +0000 UTC
```

e2e junit output

---

cluster/juju/layers/kubernetes-worker/actions.yaml
cluster/juju/layers/kubernetes-worker/actions/microbot

The action would fail randomly if not being explicit on the CLI when
launching microbot replicas.
proof
```
ubuntu@charmbox:~/builds$ juju run-action kubernetes-worker/0 microbot
Action queued with id: dc68c6bd-4e3c-4414-8844-9346abda6ef1
ubuntu@charmbox:~/builds$ juju show-action-output dc68c6bd-4e3c-4414-8844-9346abda6ef1
results:
address: microbot.104.196.127.232.xip.io
status: completed
timing:
completed: 2016-11-04 16:31:53 +0000 UTC
enqueued: 2016-11-04 16:31:48 +0000 UTC
started: 2016-11-04 16:31:53 +0000 UTC
```

Fixes for the kubernetes-worker microbot action

---

cluster/juju/layers/kubernetes-worker/config.yaml
cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py

juju config kubernetes-worker1 labels="foo=bar"
juju config kubernetes-worker2 labels="bar=baz"
you can verify the labels were set with:
kubectl get no --show-labels
This was part of a request by @rimusz

Add support for node labels

---

cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py

This will cause us to re-render addon templates and redo `kubectl apply` on kube-dns and dashboard addons.
Thanks to some nicely idempotent reactive code, looks like we can just clear the states and let 'em go. Yay!
[Juju log output](https://gist.github.com/Cynerva/d4bc4d79f9dcc05bf8161a65b0c0bfbc) from an upgrade-charm test run looks good. I was able to add annotations to the addon templates, build kubernetes-master, juju upgrade-charm, and see the annotations show up in the k8s cluster.

Remove addon states when upgrading the charm

---

cluster/juju/layers/kubernetes-e2e/actions/test

Extracing junit files to 'home/ubuntu/foobar-junit/*.xml' was going to
be painful in CI, as we would have to scrub every archive that comes
from the e2e charm. This is an attempt to clean up that output pathing
by dropping the home/ubuntu portion of the path.

Refactor the pathing on the tar archives

---

cluster/juju/layers/kubernetes-e2e/actions/test

This adds time from epoch to both start/finished portions of the log,
and parses the server version from kubectl output.

Updates the test action to embed the start/end and version

---

cluster/juju/layers/kubernetes-master/debug-scripts/kubectl
cluster/juju/layers/kubernetes-master/debug-scripts/kubernetes-master-services
cluster/juju/layers/kubernetes-master/layer.yaml
cluster/juju/layers/kubernetes-worker/debug-scripts/kubernetes-worker-services

This adds the `debug` action to `kubernetes-master`, with debug scripts to grab info for the master services and from kubectl.
Also made a small change to `kubernetes-worker` debug scripts to grab info for the `kube-proxy` service as well.
@chuckbutler @mbruzek @wwwtyro

Add debug scripts to kubernetes-master

---

cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
cluster/juju/layers/kubernetes-master/tactics/update_addons.py

Catching up with an upstream change, see https://github.com/kubernetes/kubernetes/commit/4ad06df18f3e269095f758cb9ef5f7b5f985facb
Build tested. Have not tested a deployment yet.

Update kubedns addon template names to match upstream

---

cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py

Fixes an occasional failure where kube-dns and kubernetes-dashboard can end up competing for the same IP.
Needs testing.
@mbruzek

Wait for DNS before deploying dashboard addons

---

cluster/juju/layers/kubernetes-master/tactics/update_addons.py

Used the new signature for tactics and verified that the code works with charm-tools.
I also fixed the flake8 errors in this file.
```ubuntu@b1dca1cd0f15:~/workspace/kubernetes/cluster/juju/layers/kubernetes-master$ charm build -r --no-local-layers
build: Composing into /home/ubuntu/charms
build: Destination charm directory: /home/ubuntu/charms/builds/kubernetes-master
build: Processing layer: layer:basic
build: Processing layer: layer:tls-client
build: Processing layer: layer:debug
build: Processing layer: kubernetes-master (from .)
build: Processing interface: tls-certificates
build: Processing interface: etcd
build: Processing interface: http
build: Processing interface: kubernetes-cni
build: Processing interface: kube-dns
build: Processing interface: ceph-admin
build: Processing …
```

Fixing the update_addons tactic to use new signature.

---

cluster/juju/layers/kubernetes-worker/exec.d/docker-compose/charm-pre-install

This stubs out charm-pre-install coming from layer-docker as a workaround for offline installs until https://github.com/juju/charm-tools/issues/301 is fixed.

workaround for offline installs

---

cluster/juju/layers/kubeapi-load-balancer/templates/apilb.conf

We noticed some errors in e2e testing with our internal nginx load balancer. This PR turns off proxy_buffering in the nginx configuration to speed the requests to the api-server.
https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/172

Turning off proxy buffering for issue #172.

---

cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py

Got an error on my GPU system in LXD, this fix proved to not get the error.
```
rker/0.cni-relation-changed node "juju-4bcd19-3" not labeled
unit-kubernetes-worker-0: 15:23:13 INFO unit.kubernetes-worker/0.cni-relation-changed node "juju-4bcd19-3" not labeled
unit-kubernetes-worker-0: 15:23:14 INFO unit.kubernetes-worker/0.cni-relation-changed NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is
installed and running.
unit-kubernetes-worker-0: 15:23:14 INFO unit.kubernetes-worker/0.cni-relation-changed 
unit-kubernetes-worker-0: 15:23:14 INFO unit.kubernetes-worker/0.cni-relation-changed Traceback (most recent call last):
unit-kubernetes-worker-0: 15:23:14 INFO unit.kubernetes-worker/0.cni-relation-changed   File …
```

Putting the nvidia-smi command in a try catch to avoid errors.

---

cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py

**What this PR does / why we need it**: Fix broken nagios checks.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #44322
Deploy kubernetes core, then:
```
juju deploy nrpe
juju relate nrpe:nrpe-external-master kubernetes-master:nrpe-external-master
juju relate nrpe:nrpe-external-master kubernetes-worker:nrpe-external-master
juju deploy nagios
juju relate nagios nrpe
juju expose nagios
juju config nagios password=password
```
Browse to nagios ip. Login with nagiosadmin/password.
Click 'Services' in left menu.
Confirm you see green 'snap.*.daemon' checks.
```release-note
Fix broken nagios checks.
```

Fix nagios checks.

---

cluster/juju/layers/kubernetes-master/config.yaml
cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
cluster/juju/layers/kubernetes-master/templates/default-rbac-roles.yaml
cluster/juju/layers/kubernetes-worker/lib/charms/kubernetes/flagmanager.py
cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py

Insert my Authentication work to enable token/user-pass auth in places for service components as well as the user.
This deprecates the x509 validation of TLS certs for cluster authentication, which is the precursor to authorization via RBAC, which is now enabled by default.
Kubeconfig's have been changed among the services which now live in `/root/cdk/$COMPONENTconfig ` and are not generated until the kube-control interface has been established between the worker/master.

Enable RBAC / Auth Changes

---

cluster/juju/layers/kubernetes-e2e/layer.yaml
cluster/juju/layers/kubernetes-e2e/metadata.yaml
cluster/juju/layers/kubernetes-e2e/reactive/kubernetes_e2e.py
cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py

Removes the requirement for the tls client certs, and favors a token  for auth.

Fixing e2e charm to work with token auth

---

cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py

As members depart the cluster, its important to ensure we dont have stale
tokens lying around in the auth file, as this opens a potential security
vector if those tokens were ever intercepted. This will atomically update
the file ond eparting state using the unit id as the primary key for
finding/scrubbing.

Add removal of tokens on cluster-departed event

---

cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py

Adds a missing parameter to start_worker which was introduced with the
kube-control.auth state, and scope the request for the user credentials
osn master to the 'admin' user, which is a required parameter.

Correct missing parameters

---

cluster/juju/layers/kubernetes-master/README.md
cluster/juju/layers/kubernetes-master/config.yaml
cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
cluster/juju/layers/kubernetes-worker/README.md
cluster/juju/layers/kubernetes-worker/config.yaml
cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py

Adds a `snapd_refresh` config option to k8s-master and -worker charms. This allows operators to control the frequency of k8s snap refreshes.
Fixes #
Sorry for linting the READMEs -- my editor took out extra spacing at the end of lines. Also note that the meat of this PR is the same thing we did for etcd in https://github.com/juju-solutions/layer-etcd/pull/124
```release-note
new snapd_refresh charm config to control snapd refresh frequency
```

new snapd_refresh config to control snapd refresh frequency

---

cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py

~~WAIT! This includes and extends https://github.com/juju-solutions/kubernetes/pull/143. Please review that first.~~
~~Depends on https://github.com/juju-solutions/release/pull/27.~~
This makes Dynamic Kubelet Config work.

Set kubelet dynamic-config-dir on Kubernetes 1.11+

---

cluster/juju/layers/kubernetes-master/layer.yaml
cluster/juju/layers/kubernetes-master/metadata.yaml
cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
cluster/juju/layers/kubernetes-worker/layer.yaml
cluster/juju/layers/kubernetes-worker/metadata.yaml
cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py

Adds VMware vSphere native integration via the vsphere-integrator charm
Fixes #
Depends on https://github.com/juju/layer-index/pull/40
```release-note
Support native vSphere integration in k8s charms
```

Add vSphere integration to k8s charms

---

cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py

Fixes a regression introduced by https://github.com/juju-solutions/kubernetes/commit/bc3e25146f68c3f97ce9e2198831e4a0af1e47ff#diff-e6f5b987d0e976d7b76acd341abc74c0R670, which made it where only the leader runs `configure_cdk_addons`. For non-leaders, this means the `cdk-addons.configured` state never gets set, which causes the `Waiting to retry addon deployment` status to show forever.
This PR fixes that by preventing non-leaders from ever showing the `Waiting to retry addon deployment` status.

Fix kubernetes-master non-leaders stuck on "Waiting to retry addon deployment"

---

cluster/juju/layers/kubernetes-worker/config.yaml
cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py

This adds a `blocked` status to inform the user when `kubelet-extra-args` has been configured with an arg that is deprecated in kubelet. Same for `proxy-extra-args` and kube-proxy.
For example:
```
juju config kubernetes-worker kubelet-extra-args='anonymous-auth=false`
```
results in the following charm status:
```
kubelet-extra-args: anonymous-auth is deprecated
```

juju: Add status for deprecated kubelet args

---

cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py

OpenStack clouds often have TLS termination with certs signed by
non-public CAs which cannot be verified with a standard set of CA certs
shipped in the core snap used by other snaps.
There is a way to provide a path to a ca-file in cloud.conf for k8s
in-tree OpenStack provider code which relies on gophercloud to use
that cert when creating an HTTP client for o7k endpoint communication.
The content of the CA certificate has to come from the integrator charm
which is not a subordinate, therefore, it must expose that cert over
a relation with other charms consuming data required to render
cloud.conf.

add endpoint CA certificate handling

---

cluster/juju/layers/kubeapi-load-balancer/config.yaml

Addresses https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/650
```release-note
Juju: Increase default kubeapi-load-balancer proxy_read_timeout to 10 minutes.
```

Increase default proxy_read_timeout

---

cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py

Reported by @battlemidget on a CI build:
```
$ flake8 kubernetes_worker.py 
kubernetes_worker.py:73:1: F811 redefinition of unused 'kubeproxyconfig_path' from line 64
```

Clean up flake8 warning on kubernetes-worker

---

cluster/juju/layers/kubernetes-e2e/config.yaml
cluster/juju/layers/kubernetes-master/config.yaml
cluster/juju/layers/kubernetes-worker/config.yaml

Please note that 1.12/stable is currently empty - we still need to promote 1.12.0 there.

Update Juju charms to deploy 1.12 by default

---

cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py

Fixes #
https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/666
```release-note
Fixed juju status incorrectly reporting ready status in a rare situation where CNI was not ready.
```

Fix status when cni is not ready

---

cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py

Issue if you related early enough in the cluster's lifecycle could result in the status showing error due to ceph data not being available. 
Fixes #
```release-note
Fixed an issue with an early Juju relation to a ceph cluster that was still forming.
```

Fixing an issue where ceph can appear broken

---

cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py

/kind bug
As mentioned in #183, when rbac is enabled from the get-go, we may get in a situation where the rbac resource handlers are never run. Since `switch_auth_mode` is a flag manager, it really doesn't depend on master components being started, so this PR removes that gate.
This fixes our problem because `config.changed.authorization-mode` would be handled on initial install as well as post-start, meaning the rbac flags will be set/unset in all cases.
Fixes #
```release-note …
```

auth-mode flags dont depend on started, so remove the gate

---

cluster/juju/layers/kubernetes-master/README.md
cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
cluster/juju/layers/kubernetes-master/templates/rbac-proxy.yaml

/kind bug
The previous rbac resources were created with metrics in mind, but it's more
accurate to consider them 'proxy' resources. Recall that we want to allow
our 'client' proxy user access to things like metrics and logs. To that end,
this:
- fixes the rbac config in the readme
- renames `rbac-metrics` to the more appropriate `rbac-proxy`
- adds the 'nodes/proxy' resource and relevant verbs needed to access logs
Fixes https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/642
**Does this PR introduce a user-facing …

adjust roles to allow fetching logs with rbac enabled

---

cluster/juju/layers/kubernetes-worker/build-cni-resources.sh
cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py

I've ported the original CNI build script over from here: https://github.com/juju-solutions/kubernetes-jenkins/blob/66784fbac643b710d4270d4bfca0819192b83119/resources/build-cni.sh. I think this is a better location for it.
I also changed the charm code to extract _all_ CNI plugins to /opt/cni/bin, not just the loopback one. This will make things simpler for the flannel and canal charms, as they will no longer have to bring their own copies of the core CNI plugins.

Add build script for CNI resources

---

cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
cluster/juju/layers/kubernetes-master/templates/kube-keystone.sh

Changed kube-keystone script to strip trailing whitespace as new key method returns it
Fixed potential issue with adding Webhook auth before we have the Keystone service IP resulting in a deadlock
/kind bug
```release-note
NONE
```

Added an error message when using an unsupported version of Keystone

---

cluster/juju/layers/kubernetes-worker/build-cni-resources.sh

@battlemidget This makes the built CNI resource filenames more consistent. Consider merging this before you start on the automation for CNI. Cheers.

Remove CNI version from built resource filenames

---

cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py

Fixing 
https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/703
https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/626

Extend the file descriptor limit for api server

---

cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py

> Uncomment only one, leave it on its own line:
/kind bug
Support config-changed when openstack/vsphere integrators are related.
Fixes https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/695
Related to recent vsphere integrator change https://github.com/juju-solutions/charm-vsphere-integrator/pull/2, but doesn't depend on it.
```release-note
NONE
```

update cloud config on vsphere/openstack change

---

cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py

Addressing https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/631
```
$ juju deploy canonical-kubernetes
$ juju deploy -n 3 ceph-mon
$ juju deploy -n 3 cs:ceph-osd --storage osd-devices=32G,2 --storage osd-journals=8G,1
$ juju add-relation ceph-mon ceph-osd
$ juju relate ceph-mon kubernetes-master
$ juju run --unit kubernetes-master/0 'ceph osd pool ls'
xfs-pool
ext4-pool
```

Ceph pools to be created upon ceph-mon readiness

---

cluster/juju/layers/kubeapi-load-balancer/layer.yaml
cluster/juju/layers/kubeapi-load-balancer/reactive/load_balancer.py
cluster/juju/layers/kubernetes-common/lib/charms/layer/kubernetes_common.py
cluster/juju/layers/kubernetes-e2e/layer.yaml
cluster/juju/layers/kubernetes-e2e/reactive/kubernetes_e2e.py
cluster/juju/layers/kubernetes-master/layer.yaml
cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
cluster/juju/layers/kubernetes-worker/layer.yaml
cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py

Depends on https://github.com/juju-solutions/layer-tls-client/pull/15
Depends on https://github.com/juju-solutions/layer-easyrsa/pull/16
/kind cleanup
The global client certificate was poor design because it was shared with multiple applications.  This fixes it so that the applications get their own client certificate.
```release-note
NONE
```

Remove use of global / shared client certificate

---

cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py

/kind bug
It can be the case that some but not all pods go to Running even though the NetworkUnavailable issue was hit.  This fixes it so the workaround will still be applied if needed.
```release-note
NONE
```

Fix GCP NetworkUnavailable hack when only some pods pending

---

cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py

/kind bug
This will prevent the charm from failing hard if a subordinate wipes out the worker's refresh timer, and it should recover gracefully by restoring the desired value.
It's still possible for the operator to set the config on both the principal and subordinate, which would lead to units possibly having different refresh timers, but at that point there isn't really much we can do.
Fixes juju-solutions/bundle-canonical-kubernetes#657
```release-note
NONE
```

Improve handling of snap refresh window when wiped out by subordinate

---

cluster/juju/layers/kubernetes-master-worker-base/reactive/kubernetes_master_worker_base.py
cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py

/kind bug
The fix in #212 should apply equally to both master and worker, so this
moves it to the base.
```release-note
NONE
```

Replicate snap refresh timer fix for master

---

cluster/juju/layers/kubernetes-master-worker-base/reactive/kubernetes_master_worker_base.py

I got an ImportError on `charms.layer.leadership`. I'm pretty sure the correct name is `charms.leadership` as seen here: https://git.launchpad.net/layer-leadership/tree/lib

Fix import for charms.leadership

---

cluster/juju/layers/kubernetes-master-worker-base/exec.d/docker-compose/charm-pre-install

First reported in https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/625, if somehow this script gets marked executable, layer-basic will run it, and we'll get an OSError because of the lack of shebang.
Under normal circumstances, we'll never run this file because it's not executable, but it's possible an operator could have a umask that makes all files exe by default. Untarring a shrinkwrap tarball in this scenario would cause this to get a +x, and proceed to blow up at deploy time.
To be on the safe side, let's just add a shebang. This script doesn't do anything, so even if it is unintentionally executed, no harm done.

add shebang to docker-compose pre-install stub

---

cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py

This fixes the following error spam from metrics-server:
```
W0220 18:46:36.386183       1 x509.go:172] x509: subject with cn=system:kube-apiserver is not in the allowed list: [client]
W0220 18:46:36.494335       1 x509.go:172] x509: subject with cn=system:kube-apiserver is not in the allowed list: [client]
```
The CN was changed from `client` to `system:kube-apiserver` here: https://github.com/juju-solutions/kubernetes/pull/207

Fix wrong name in requestheader-allowed-names

---

cluster/juju/layers/kubernetes-common/lib/charms/layer/kubernetes_common.py

Depends on https://github.com/juju-solutions/interface-openstack-integration/pull/10
Depends on https://github.com/juju-solutions/charm-openstack-integrator/pull/15
/kind feature
Handles block storage config options proxied from OpenStack Integration charm.
Addresses https://bugs.launchpad.net/charm-openstack-integrator/+bug/1809349
```release-note
NONE
```

Add block storage options for OpenStack

---

cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py

We move to 0.22.0 tag for amd64 and arm64. For s390x and ppc64el the latest tag is 0.20.0.

Update the default nginx-ingress controller

---

cluster/juju/layers/kubernetes-master/config.yaml
cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py

/kind feature
Adds a configuration option dashboard-auth to kubernetes-master charm for selecting the dashboard auth method.
```release-note
Added dashboard-auth configuration option. Defaults to auto and will select basic unless keystone is related, when it then selects token authentication. Can also be set to either basic or token to force the authentication mode.
```

Adding dashboard auth option

---

cluster/juju/layers/kubeapi-load-balancer/reactive/load_balancer.py
cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py

easyrsa would puke if you had no configured virtual IP or dns for hacluster, but had hacluster related. It blew up because we added an extra sans of an empty string, which resulted in a call to create a cert with an empty name, which easyrsa didn't like of course. This fixes that by checking for no config options at all set.
/kind bug
```release-note
NONE
```

Fixing an issue with easyrsa and hacluster

---

cluster/juju/layers/kubernetes-master/actions.yaml
cluster/juju/layers/kubernetes-master/actions/get-kubeconfig

/kind feature
Once the k8s cluster is completed the config with login credentials is stored at `/home/ubuntu/config`. With this juju action we enable users to pull out credentials to connect to the cluster. 
Alternatively, we could use `juju scp --proxy=true` but python libjuju (https://pythonlibjuju.readthedocs.io/en/latest/_modules/juju/machine.html#Machine.scp_from) doesn't support *proxy* yet as we require it.
NONE
Usecase has been discussed with @tvansteenburgh 
```release-note
Add new get-kubeconfig action to kubernetes-master
```

add new get-kubeconfig action to kubernetes-master

---

cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py

1.5 doesn't exist for s390x, let's go back to 1.4:
https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/defaultbackend-s390x?gcrImageListsize=30
Confirmed much pod success on s3lp3:
```
$ kubectl describe pod/default-http-backend-kubernetes-worker-55b4bf4d47-vdvmk -n ingress-nginx-kubernetes-worker
Name:           default-http-backend-kubernetes-worker-55b4bf4d47-vdvmk
Namespace:      ingress-nginx-kubernetes-worker
...
Status:         Running
...
Image:          k8s.gcr.io/defaultbackend-s390x:1.4
```
/kind bug
```release-note
NONE
```

fix defaultbackend-s390x image
