juju-solutions/kubernetes

- cluster/juju/layers/kubernetes/tests/tests.yaml
Reverts juju-solutions/kubernetes#3
> Revert "Automated testing shouldn't bootstrap"

- cluster/juju/layers/kubernetes/templates/master.json
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
```release-note
```
> Juju release 1.4

- cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
- cluster/juju/layers/kubernetes-master/templates/kubedns-rc.yaml
- cluster/juju/layers/kubernetes-master/templates/kubedns-svc.yaml
Updates that should work a little better.
> Adding dns templates, and making code render them.

- cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
I found the problem, and fixed the problem.
> Actually call the install command for kubectl.

- cluster/juju/layers/kubernetes-master/metadata.yaml
- cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
Adds the `kubernetes` resource
Adds provides, requires relations to metadata
> Adds Resources and Relations

- cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
Added basic_auth and known_tokens csv files.
> Adding auth and token code.

- cluster/juju/layers/kubernetes-master/templates/kube-apiserver.defaults
- cluster/juju/layers/kubernetes-master/templates/kube-controller-manager.service
- cluster/juju/layers/kubernetes-master/templates/kube-scheduler.service
Removes the TLS flags from the apiserver flags
tweaks the dependencies on service files for the controller-manager and
scheduler
> Tweaks to the service definitions and defaults

- cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
- cluster/juju/layers/kubernetes-master/templates/kube-apiserver.service
- cluster/juju/layers/kubernetes-master/templates/kube-controller-manager.defaults
- cluster/juju/layers/kubernetes-master/templates/kube-controller-manager.service
- cluster/juju/layers/kubernetes-master/templates/kube-scheduler.service
this adds some additional status messaging
adds missing imports
refactors systemd templates
> Make systemd templates closer aligned to upstream

- cluster/juju/layers/kubernetes-master/layer.yaml
- cluster/juju/layers/kubernetes-master/metadata.yaml
- cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
- cluster/juju/layers/kubernetes-master/templates/kube-apiserver.defaults
- cluster/juju/layers/kubernetes-master/templates/kube-apiserver.service
> First run at adding tls client interface to master.

- cluster/juju/layers/kubernetes-worker/copyright
- cluster/juju/layers/kubernetes-worker/layer.yaml
- cluster/juju/layers/kubernetes-worker/lib/charms/kubernetes/flagmanager.py
- cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py
- cluster/juju/layers/kubernetes-worker/templates/kubelet-kubeconfig
Adds tls-client layer Configures kubelet for certificate authentication
with the master renames ServerOpts to charms.kubernetes.flagmanager
> tls-client integration

- cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
- cluster/juju/layers/kubernetes-master/templates/kubernetes-dashboard.yaml
Also fixes a bug when interrogating for nodes
> Adds kubernetes dashboard addon

- cluster/juju/layers/kubeapi-load-balancer/layer.yaml
- cluster/juju/layers/kubeapi-load-balancer/metadata.yaml
- cluster/juju/layers/kubeapi-load-balancer/reactive/load_balancer.py
- cluster/juju/layers/kubernetes-master/layer.yaml
- cluster/juju/layers/kubernetes-master/metadata.yaml
- cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
Adding kubeconfig creation for the kuberentes-master
Adding public-address interface to the loadbalancer and kubernetes-master
Please review for errors as it is very late.
> Adding kubeconfig code and loadbalancer interface.

- cluster/juju/layers/kubeapi-load-balancer/layer.yaml
- cluster/juju/layers/kubeapi-load-balancer/metadata.yaml
- cluster/juju/layers/kubeapi-load-balancer/reactive/load_balancer.py
- cluster/juju/layers/kubernetes-master/layer.yaml
- cluster/juju/layers/kubernetes-master/metadata.yaml
- cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
@mbruzek this rolls up your contribution in #30 and I patched the two holdout bugs I found. We can merge #30 and then merge this to stabilize the bundle i believe
> Patches to land routing through the loadbalancer relation in the user credentials

- cluster/juju/layers/kubeapi-load-balancer/layer.yaml
- cluster/juju/layers/kubeapi-load-balancer/reactive/load_balancer.py
- cluster/juju/layers/kubernetes-master/README.md
- cluster/juju/layers/kubernetes-master/copyright
- cluster/juju/layers/kubernetes-master/layer.yaml
- cluster/juju/layers/kubernetes-master/metadata.yaml
- cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
- cluster/juju/layers/kubernetes-worker/layer.yaml
- cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py
- cluster/juju/layers/kubernetes-worker/templates/kubeconfig
Moved the certificate paths to the layer.
Added logic to wait for the certificates to exist before using them.
Fixed spelling and proof errors.
> Adding tls to master, worker, loadbalancer and fixing some proof errors.

- cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
- cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py
The services were started but will not survive unit interruption, reboots,
etc. as the systemd services were not enabled on boot
> Adds systemctl.enable stanza to systemd units

- cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py
@chuckbutler @mbruzek @Cynerva 
Tested, works.
Deletes the current unit's k8s node on the stop hook.
> Delete k8s node when unit is stopped.

- cluster/juju/layers/kubernetes-master/actions/create-rbd-pv
- cluster/juju/layers/kubernetes-master/lib/charms/kubernetes/flagmanager.py
Updates the action-set with grammar fix
Fixes an extended comment failing lint
> Corrects linting errors and messaging grammar

- cluster/juju/layers/kubernetes-worker/lib/charms/kubernetes/flagmanager.py
Fixes an extended comment that was failing lint
> Corrects a lint error

- cluster/juju/layers/kubeapi-load-balancer/layer.yaml
- cluster/juju/layers/kubernetes-master/layer.yaml
- cluster/juju/layers/kubernetes-worker/layer.yaml
- cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py
Adding the nfs-common package to resolve issue https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/72
Normalizing our layer.yaml files
Fixing lint errors introduced in recent commits.
> Adding nfs common

- cluster/juju/layers/kubernetes-master/actions/create-rbd-pv
@chuckbutler @mbruzek action fixes from our debug session today
> fix create-rbd-pv

- cluster/juju/layers/kubernetes-master/actions.yaml
* make name and size be required
* add minLength and minimum to name and size
* rename `options:` to `params:` so the validation is picked up
> Validate name and size for create-rbd-pv action

- cluster/juju/layers/kubernetes-master/actions.yaml
- cluster/juju/layers/kubernetes-master/actions/create-rbd-pv
@mbruzek @chuckbutler @Cynerva
> RBD action size validation

- cluster/juju/layers/kubernetes-e2e/actions.yaml
- cluster/juju/layers/kubernetes-e2e/actions/test
- cluster/juju/layers/kubernetes-e2e/layer.yaml
@chuckbutler @mbruzek Ready for review
> run e2e tests in parallel

- cluster/juju/layers/kubernetes-master/README.md
- cluster/juju/layers/kubernetes-master/actions.yaml
- cluster/juju/layers/kubernetes-master/actions/restart
The kubernetes-master README.md was very out of date. I updated the document with this pull request and plan to move sections of this to the worker, please review and let me know how to write better English words.
> Updates to the kubernetes-master README.md

- cluster/juju/layers/kubernetes-master/actions.yaml
- cluster/juju/layers/kubernetes-master/templates/influxdb-grafana-controller.yaml
- cluster/juju/layers/kubernetes-master/templates/influxdb-service.yaml
- cluster/juju/layers/kubernetes-master/templates/kubedns-rc.yaml
- cluster/juju/layers/kubernetes-master/templates/kubedns-svc.yaml
- cluster/juju/layers/kubernetes-master/templates/kubernetes-dashboard.yaml
Making the templates current between the kubernetes/kubernetes and kubernetes/dashboard repos.
https://github.com/kubernetes/kubernetes
https://github.com/kubernetes/dashboard
> Updating the action, and templates to get current with k8s upstream.

- cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py
See https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/122
> Addresses issue 122

- cluster/juju/layers/kubernetes-e2e/layer.yaml
- cluster/juju/layers/kubernetes-e2e/reactive/kubernetes_e2e.py
~~Looking into some failing tests - don't merge yet.~~
> e2e ginkgo resource

- cluster/juju/layers/kubernetes-master/layer.yaml
- cluster/juju/layers/kubernetes-worker/layer.yaml
This nievely resolves
https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/135
> Add the 'socat' package to both worker and master

- cluster/juju/layers/kubernetes-worker/debug-scripts/docker
Moving this debug script to layer-docker. See https://github.com/juju-solutions/layer-docker/pull/97
@chuckbutler @mbruzek @wwwtyro
> Remove docker debug script

- cluster/juju/layers/kubernetes-master/debug-scripts/kubernetes-master-services
- cluster/juju/layers/kubernetes-worker/debug-scripts/kubernetes-worker-services
Tiny update to the debug scripts here. Tested, ready to merge.
> Use verbose copy in debug scripts

- cluster/juju/layers/kubernetes-master/tactics/update_addons.py
Just knocking this off my list quick. Fix for https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/169, low priority.
New output:
```
build: Composing into /home/gkk/work/juju-repo/charms
build: Destination charm directory: /home/gkk/work/juju-repo/charms/builds/kubernetes-master
build: Processing layer: layer:basic
build: Processing layer: layer:tls-client
build: Processing layer: layer:debug
build: Processing layer: kubernetes-master
build: Processing interface: tls-certificates
build: Processing interface: etcd
build: Processing interface: http
build: Processing interface: kubernetes-cni
build: Processing interface: kube-dns
build: Processing interface: ceph-admin
build: Processing interface: public-address
tactics.update_addons: Cloning …
```
> Make UpdateAddonsTactic less verbose

- cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py
https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/166
> add support for kube-proxy cluster-cidr option

- cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py
Not a complete fix, opening for discussion
> Fix handling of kubernetes-worker.restart-needed state

- cluster/juju/layers/kubernetes-worker/layer.yaml
- cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py
Some clean-up on the worker. Removed client cert please be extra careful. Thanks.
> Cleaning up worker after going to auth tokens

- cluster/juju/layers/kubernetes-e2e/reactive/kubernetes_e2e.py
Refactors e2e to use token auth, and to request the proper auth level with
that token.
> Add support for e2e requesting elevated privs

- cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
- cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py
handle upgrades for existing deployments
Non-rbac to rbac upgrade comes with some potential race conditions. It's best if you upgrade the master unit first, then additionally apply the worker upgrades. Token generation happens during the kube-control relation cycle and they will attempt autonomous registration.
> Upgrade path for existing deployments

- cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py
last piece of the rbac puzzle to migrate ingress into the kube-system ns and properly remove the existing ingress controller
> Rbac upgrade

- cluster/juju/layers/kubernetes-worker/layer.yaml
**What this PR does / why we need it**: Adding the leadership layer to the Juju kubernetes worker
Fixes #
```release-note
NONE
```
> Add leadership layer to kubernetes-worker

- cluster/juju/layers/kubernetes-worker/config.yaml
- cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py
Tested, seems to be working as designed.
> juju: Add kubelet-extra-config to kubernetes-worker

- cluster/juju/layers/kubernetes-master/layer.yaml
- cluster/juju/layers/kubernetes-master/metadata.yaml
- cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
- cluster/juju/layers/kubernetes-worker/layer.yaml
- cluster/juju/layers/kubernetes-worker/metadata.yaml
- cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py
Adds Microsoft Azure native integration via the azure-integrator charm.
Also tries to defer starting components if cloud integration is pending but not yet complete, to avoid unnecessary restarts.
Depends on juju-solutions/charm-azure-integrator#15 and juju-solutions/interface-azure-integration#4
> Add Azure Integrator support to k8s charms

- cluster/juju/layers/kubernetes-common/README.md
- cluster/juju/layers/kubernetes-common/layer.yaml
- cluster/juju/layers/kubernetes-common/lib/charms/layer/kubernetes_common.py
The plan is to get the lib in and the index updated before making the changes to remove the common code in the master and worker charms to prevent moving pieces breaking.
```release-note
Adding common lib layer for Kubernetes charms
```
> First commit of common lib for kubernetes charms

- cluster/juju/layers/kubernetes-common/lib/charms/layer/kubernetes_common.py
- cluster/juju/layers/kubernetes-master/layer.yaml
- cluster/juju/layers/kubernetes-master/metadata.yaml
- cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
- cluster/juju/layers/kubernetes-worker/layer.yaml
- cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py
Fixes #
Need to wait for https://github.com/juju-solutions/charm-flannel/pull/47.
```release-note
Kubernetes master charm now deploys kube-proxy. This will allow the master to communicate with services on the cluster.
```
> Adding kube-proxy to kubernetes-master

- cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py
Fixes https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/655
Tested with:
* 1.11 on bionic
* 1.9 on bionic, upgraded to 1.10
* 1.11 on xenial
> Workaround DNS issue on kubernetes-worker on bionic

- cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py
Following the suggestion here: https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/655#issuecomment-424364893
Tested and ready for merge.
> Fix kubernetes-worker kube-dns workaround applying when it shouldn't

- cluster/juju/layers/kubernetes-master/debug-scripts/kubernetes-master-services
- cluster/juju/layers/kubernetes-master/layer.yaml
Spotted these while looking into a failure on CI.
> Add kube-proxy to kubernetes-master debug-scripts and cdk-service-kicker config

- cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
- cluster/juju/layers/kubernetes-master/templates/service-always-restart.conf
This builds on the work done by @hyperbolic2346 in https://github.com/juju-solutions/kubernetes/pull/165, with a couple fixes on top that I think are needed. Cheers.
> Making master services always restart, plus fixes

- cluster/juju/layers/kubernetes-common/lib/charms/layer/kubernetes_common.py
- cluster/juju/layers/kubernetes-master/config.yaml
- cluster/juju/layers/kubernetes-master/layer.yaml
- cluster/juju/layers/kubernetes-master/metadata.yaml
- cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
- cluster/juju/layers/kubernetes-master/templates/keystone-api-server-webhook.yaml
- cluster/juju/layers/kubernetes-master/templates/kube-keystone.sh
Adds Keystone support to CDK.
Fixes #
Need to wait on https://github.com/juju-solutions/cdk-addons/pull/58 to merge before pulling this in.
```release-note
Keystone support is available with a relation to the kubernetes-master charm.
```
> Adding keystone support

- cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
> Uncomment only one, leave it on its own line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake
Fixes #
https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/681
```release-note
Fixed issue with juju deployed Kubernetes with multiple master units and Keystone
```
> Fixing Keystone integration with multiple masters.

- cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
Fixes https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/675
> Revert kubernetes-master to old ceph integration on k8s 1.11, 1.10

- cluster/juju/layers/kubernetes-master/templates/kube-keystone.sh
> Uncomment only one, leave it on its own line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
/kind failing-test
> /kind feature
> /kind flake
Adds boilerplate to kube-keystone.sh
Fixes #
```release-note
NONE
```
> Adding boilerplate

- cluster/juju/layers/kubeapi-load-balancer/layer.yaml
- cluster/juju/layers/kubeapi-load-balancer/reactive/load_balancer.py
- cluster/juju/layers/kubernetes-common/lib/charms/layer/kubernetes_common.py
- cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
/kind bug
interface-http recently switched to being an Endpoint class (https://github.com/juju-solutions/interface-http/pull/10); update references to `relation_name`.
Fixes #
While making this endpoint change, I also removed the duplicate `get_ingress_address` function in favor of the one available in our common lib.
```release-note
NONE
```
> use common lib methods; s/relation/endpoint as needed

- cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
- cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py
/kind bug
Handle changes from the OpenStack Integrator charm to credential or config data.
Fixes juju-solutions/charm-openstack-integrator#10
Depends on juju-solutions/interface-openstack-integration#9
NONE
> Handle upstream changes from OpenStack Integrator

- cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
when no keystone relations exist, we would spam about it. Fixing it for @kwmonroe
Also added some detail to the waiting for pods message to include the number
> Uncomment only one, leave it on its own line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake
Fixes #
```release-note
NONE
```
> Fixing spam related to keystone

- cluster/juju/identify-leaders.py
- cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
- cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py
- cluster/juju/return-node-ips.py
/kind flake
Fix flake8 errors under `cluster/juju`
NONE
> Fix lint errors in cluster/juju

- cluster/juju/layers/kubernetes-common/lib/charms/layer/kubernetes_common.py
- cluster/juju/layers/kubernetes-worker/README.md
- cluster/juju/layers/kubernetes-worker/layer.yaml
- cluster/juju/layers/kubernetes-worker/metadata.yaml
- cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py
/kind feature
Support relation between k8s and the docker-registry charm.
Fixes #
```release-note
Support the docker-registry interface
```
> docker-registry support

- cluster/juju/layers/kubernetes-common/lib/charms/layer/kubernetes_common.py
- cluster/juju/layers/kubernetes-master/layer.yaml
- cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
/kind feature
Adds support for encrypting data at rest using Vault.
Depends on: https://github.com/juju-solutions/layer-vaultlocker/pull/1
Depends on: https://github.com/juju-solutions/layer-vault-kv/pull/1
```release-note
Juju charms now support encryption at rest with keys protected by Vault
```
> Encryption at rest

- cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
- cluster/juju/layers/kubernetes-master/templates/rbac-proxy.yaml
Fixing https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/696
> Adding 'create' verb to proxy-clusterrole

- cluster/juju/layers/kubernetes-master/metadata.yaml
- cluster/juju/layers/kubernetes-worker/config.yaml
- cluster/juju/layers/kubernetes-worker/metadata.yaml
- cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py
https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/585
~~Do not merge yet as need testing when `nvidia-docker2` package is fixed.~~
> Removing allow privileged from worker charm

- cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
Addresses https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/164
> Set status when writing kubeconfig file

- cluster/juju/layers/kubernetes-worker/registry-configmap.yaml
/kind bug
Fix name, namespace and data in registry action. This is needed for newer versions of nginx-ingress.
Fixes https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/721
```release-note
NONE
```
> Fix name, namespace and data in registry action.

- cluster/juju/layers/kubeapi-load-balancer/layer.yaml
- cluster/juju/layers/kubeapi-load-balancer/reactive/load_balancer.py
- cluster/juju/layers/kubernetes-common/lib/charms/layer/kubernetes_common.py
- cluster/juju/layers/kubernetes-master/layer.yaml
- cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
- cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
/kind feature
> /kind flake
Adds hacluster support
Requires https://github.com/juju-solutions/layer-hacluster/pull/1, https://github.com/juju-solutions/interface-public-address/pull/3, and https://github.com/juju-solutions/interface-http/pull/17
```release-note
Added support for hacluster, which allows for virtual IPs in front of the control plane with or without load balancers.
```
> Adding hacluster support

- cluster/juju/layers/kubernetes-master/config.yaml
- cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
Depends on https://github.com/juju-solutions/cdk-addons/pull/83
This adds CoreDNS support for CDK 1.14.
* Removed enable-kube-dns config
* Added dns-provider config (documented in config.yaml)
> Add CoreDNS support

- cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
Fixes https://bugs.launchpad.net/charm-kubernetes-master/+bug/1822001
> Fix unvalidated dns-provider input

- cluster/juju/layers/kubernetes-master/config.yaml
Also added an example command.
/kind cleanup
FIxes configuration parameter information.
Fixes https://bugs.launchpad.net/charm-kubernetes-master/+bug/1822215
```release-note
Updated keystone-ssl-ca configuration option to reflect proper usage. Note that the CA certificate now needs to be embedded into the configuration and not a filename.
```
> Updating configuration parameter details to correct for usage.
